### ISSUE TITLE
Grant Type Failure

### ISSUE THREAD

**Issue by morgan-legal** [trivago/Heimdallr.swift#109]
Hi there!

First, kudos on the library!! 

I do have an issue with the `requestAccessToken(username,password)` method. I'm having a failure: `failure: grant_type must be client_credentials, authorization_code or refresh_token`

```
      heimdallr.requestAccessToken(username: username, password: password) { result in
            switch result {
            case .success:
                print("success")
            case .failure(let error):
                print("failure: \(error.localizedDescription)")
            }
        }
```

Any ideas ?

Thanks,
Morgan

**Comment by morgan-legal** [comment]
My bad... it was because Spotify only support the 3 grant_type above.

**Comment by felixjendrusch** [comment]
happy listening.
