### ISSUE TITLE
Remove Argo?

### ISSUE THREAD

**Issue by marcelofabri** [trivago/Heimdallr.swift#90]
Hi there!

I'm currently adding Heimdallr to our project and we already use [another mapping framework](https://github.com/lyft/mapper). Since dynamic frameworks add a considerable overhead when loading, I was think if it was possible to remove Argo as dependency here.

My main motivation is that the models seem to be simple enough to parse them manually instead and it would keep the library simpler, avoiding:

1. The overhead of another dynamic framework
2. Caring about if Argo updated to Swift X.Y
3. Potential conflicts between the Argo version used by this project and the user's project

This shouldn't even be a breaking change, since it's just an implementation detail.

I don't know the history, but it seems that on #16, everyone agreed that dependencies were fine, but https://github.com/trivago/Heimdallr.swift/commit/2be58cbe3d78903c282532ff0db8809a51db35e6 removed KeychainAccess in favor of a custom Keychain wrapper.

If response is positive to this issue, I'm willing to work on this and open a PR.

Thanks!

**Comment by hffmnn** [comment]
Great Idea!

I think you are absolutely right and give this definitely a 👍!

Thanks a lot for your effort!
