### ISSUE TITLE
Prevent firing multiple requests?

### ISSUE THREAD

**Issue by marcelofabri** [trivago/Heimdallr.swift#92]
From what I've seen in the code, no special treatment is done to prevent multiple network calls being fired in `authenticateRequest`.

This can be a problem, as a server can invalidate one of the returned tokens. Should the library handle this?

**Comment by Stengo** [comment]
Great catch! We looked into this and I just opened a pull request that should fix the issue.

**Comment by felixjendrusch** [comment]
See #93.

**Comment by marcelofabri** [comment]
Fixed by #93
