### ISSUE TITLE
FYI Xcode 8/iOS 10 Keychain issues

### ISSUE THREAD

**Issue by dccarmo** [trivago/Heimdallr.swift#98]
I was having issues authenticating my requests, and after spending some time debugging I found out that the issue is that the Keychain was giving an error when storing a new value. Apparently this is a known issue with iOS 10, there are some threads discussing this here:

https://forums.developer.apple.com/message/179846

https://forums.developer.apple.com/thread/51071

Workaround usually is to add the Keychain Entitlement, but it doesn't solve in my case because I use Heimdallr in a framework.

Thought I'd create this here if anyone else is running into the same issues (Heimdallr doesn't seem to be reporting this error.)

**Comment by hffmnn** [comment]
Hi dccarmo,

thanks for reporting this. We discussed this in https://github.com/trivago/Heimdallr.swift/pull/95 and it seems to be a problem on Apple's side.
Just to be sure: Heimdallr does not work for you in an application on Simulator AND Device?

**Comment by Ingibjorg** [comment]
@hffmnn and @dccarmo I'm experiencing the same issue. Heimdallr works on device but not on simulator for me.

**Comment by dccarmo** [comment]
I wasn't able to test on my device because I can't Unit Test my framework in a device, but I'm assuming it should work.
